# -*- coding: utf-8 -*-
"""
Created on Mon Oct 30 10:44:00 2017

@author: Edward

Pentagonal numbers are generated by the formula, Pn=n(3n−1)/2. The first ten pentagonal numbers are:

1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...

It can be seen that P4 + P7 = 22 + 70 = 92 = P8. However, their difference, 70 − 22 = 48, is not pentagonal.

Find the pair of pentagonal numbers, Pj and Pk, for which their sum and difference are pentagonal and D = |Pk − Pj| is minimised; what is the value of D?

"""

def pentagonal(n):
    return int(n*(3*n-1)/2)

    

    
pentagonals = set()
for i in range(1,1000000):
    pentagonals.add(pentagonal(i))

best_j_k = None
best_diff = list(pentagonals)[-1]


for j in range(1, 10000):
    pj = pentagonal(j)
    for k in range(1, 10000):
        pk = pentagonal(k)
        s = pj + pk
        if abs(pj-pk) < best_diff and (pj + pk) in pentagonals and abs(pj - pk) in pentagonals:
            best_j_k = (j,k)
            best_diff = abs(pj-pk)

print(best_diff)
print(best_j_k)
print(pentagonal(best_j_k[0]))
print(pentagonal(best_j_k[1]))



        