# -*- coding: utf-8 -*-
"""
Created on Mon Oct 30 11:22:55 2017

@author: Edward

Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:

Triangle	 	Tn=n(n+1)/2	 	1, 3, 6, 10, 15, ...
Pentagonal	 	Pn=n(3n−1)/2	 	1, 5, 12, 22, 35, ...
Hexagonal	 	Hn=n(2n−1)	 	1, 6, 15, 28, 45, ...
It can be verified that T285 = P165 = H143 = 40755.

Find the next triangle number that is also pentagonal and hexagonal.

"""


from myutils import  triagonal, pentagonal, hexagonal


triagonals = dict()
pentagonals = set()
hexagonals = set()

for i in range(1,100000):
    triagonals[triagonal(i)] = i
    pentagonals.add(pentagonal(i))
    hexagonals.add(hexagonal(i))
    
for tri in triagonals.keys():
    if tri in pentagonals and tri in hexagonals:
        print(triagonals[tri], tri)

