#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sat Nov 17 14:58:05 2018

@author: edward

Triangle, square, pentagonal, hexagonal, heptagonal, and octagonal numbers are all figurate (polygonal) numbers and are generated by the following formulae:

Triangle	 	P3,n=n(n+1)/2	 	1, 3, 6, 10, 15, ...
Square	 	P4,n=n2	 	1, 4, 9, 16, 25, ...
Pentagonal	 	P5,n=n(3n−1)/2	 	1, 5, 12, 22, 35, ...
Hexagonal	 	P6,n=n(2n−1)	 	1, 6, 15, 28, 45, ...
Heptagonal	 	P7,n=n(5n−3)/2	 	1, 7, 18, 34, 55, ...
Octagonal	 	P8,n=n(3n−2)	 	1, 8, 21, 40, 65, ...
The ordered set of three 4-digit numbers: 8128, 2882, 8281, has three interesting properties.

The set is cyclic, in that the last two digits of each number is the first two digits of the next number (including the last number with the first).
Each polygonal type: triangle (P3,127=8128), square (P4,91=8281), and pentagonal (P5,44=2882), is represented by a different number in the set.
This is the only set of 4-digit numbers with this property.
Find the sum of the only ordered set of six cyclic 4-digit numbers for which each polygonal type: triangle, square, pentagonal, hexagonal, heptagonal, and octagonal, 
is represented by a different number in the set.
"""


from myutils import Figurate

tris = {}
squares = {}
pents = {}
hexes = {}
hepts = {}
octs = {}

pairs = [(tris, Figurate.triagonal),
         (squares, Figurate.square),
         (pents, Figurate.pentagonal),
          (hexes, Figurate.hexagonal),
          (hepts, Figurate.heptagonal),
          (octs, Figurate.octagonal)]


for i in range(1000):
    for cont, func in pairs:
        n = func(i)
        if n > 999 and n < 10000:
            cont[n] = False
    
    
def recursive_check(chain, conts):
    
    length = 0
    if len(chain) == 6:
        if int(str(chain[0])[:2]) == int(str(chain[-1])[2:]):
            print(chain, sum(chain))
        return 1
    prev = chain[-1]
    prev = int(str(prev)[2:])
    for i in range(10, 100):
        to_check = int(str(prev)+str(i))
        
        for cont, _ in pairs:
            if (to_check not in chain and
                cont not in conts and
                to_check in cont.keys() and
                not cont[to_check]):
                #cont[to_check] = True
                
                length = recursive_check(chain+[to_check], conts+[cont])
    return length

for tri in tris.keys():
    chain = [tri]
    conts = [tris]
    tris[tri] = True
    
    l = recursive_check(chain, conts)
    if l==6:
        print(tri)

